### ISSUE TITLE
Streamlink 3.0.0 has broken it

### ISSUE THREAD

**Issue by phrwn** [laurencee/Livestream.Monitor#71]
Example output:

`Launching streamlink....
'streamlink.exe https://www.twitch.tv/adam_ak/ Best'
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 17, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 22, in <module>
    import streamlink.logger as logger
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\__init__.py", line 21, in <module>
    from streamlink.api import streams
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\api.py", line 1, in <module>
    from streamlink.session import Streamlink
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\session.py", line 18, in <module>
    from streamlink.utils.l10n import Localization
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\utils\l10n.py", line 4, in <module>
    from pycountry import countries, languages
  File "C:\Program Files (x86)\Streamlink\pkgs\pycountry\__init__.py", line 12, in <module>
    __version__ = pkg_resources.get_distribution("pycountry").version
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Program Files (x86)\Streamlink\pkgs\pkg_resources\__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycountry' distribution was not found and is required by the application

ERROR occurred in streamlink: Manually close this window when you've finished reading the streamlink output.`

**Comment by laurencee** [comment]
I don't seem to be able to run streamlink 3.0 even without Livestream Monitor, I get the same error. 😱

**Comment by laurencee** [comment]
@phrwn https://github.com/streamlink/streamlink/issues/4179

**Comment by phrwn** [comment]
I get a brief command window if I run streamlink.exe, nothing if I run streamlinkw.exe (which I think is to be expected). Trying to run a stream via Streamlink for Twitch GUI and I get 'Unexpected version check output', which is less informative than Livestream Monitor, but notable for not working either.

**Comment by laurencee** [comment]
Fixed in their latest release: https://github.com/streamlink/streamlink/releases/tag/3.0.1

If you have an existing config file you'll need to comment out/remove lines relating to `rtmpdump` and `hds`

**Comment by phrwn** [comment]
That does work now, but I'm getting significant stutter. I had noticed this before updating, just recently - not sure if it's a Windows 11 thing, since that's all I've changed. But just updating this now and commenting out lines in the config file as suggested (doesn't work at all otherwise) the stutter is really bad. Stream stops for a couple of seconds every five or so seconds.

**Comment by laurencee** [comment]
Check that you have the following in your config: https://github.com/laurencee/Livestream.Monitor#suggested-streamlinklivestreamer-configuration

Besides that, there are 2 main things I can think of:
1. You can use VLC for now and uncomment the line; `#player-args=--file-caching=5000`. The stream will be delayed a few seconds from normal, but it may address the stuttering.
2. Your ISP is having some temporary issue with its routing to the twitch network, not much you can do about that :(

I have some friends in Singapore had have had routing issues recently and were getting stuttering watching certain twitch streams.

**Comment by phrwn** [comment]
Ok I didn't have the low-latency of the hls-live-edge settings in my config, which seems to have fixed it. I did notice there was no problem when I opened a stream that did not need to pause to skip pre-roll content, but now everything seems to work on all streams. Thank you for you help, as ever.
