### ISSUE TITLE
Error Getting VODs

### ISSUE THREAD

**Issue by numberneuf** [laurencee/Livestream.Monitor#82]
As soon as I begin typing in the Stream text box on the top of the "Vod Viewer" tab, I receive an error. 

As I started typing a word that started with "c", I am immediately met with: 

```
Error Getting Vods
Error occurred getting vods from api Itwitchtvl for channel 'cl.
ExternalAPls.HttpRequestWithStatusException:
Request","status":400,"message":"Channelld is not a valid number c"}
at ExternalAPls.HttpClientExtensions.<EnsureSuccessStatusCodeAsync>d_4.MoveNext() in E:
\Programming\Git\Livestream.Monitor\ExternalAPls\HttpClientExtensions.cs:line 56
- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
(Task task)
at ExternalAPls.HttpClientExtensions.<ExecuteRequest>d_3'1.MoveNext() in E:\Programming
\Git\Livestream.Monitor\ExternalAPls\HttpClientExtensions.cs:line 37
- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompiIerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
(Task task)
at ExternalAPls.TwitchTv.Helix.TwitchTvHelixHelixReadonlyClient.<GetVideos>d_9.MoveNext()
in E:\Programming\Git\Livestream.Monitor\ExternalAPls\TwitchTv\Helix
\ TwitchTvHelixHelixReadonlyClient.cs:line 188
- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompiIerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
(Task task)
at Livestream.Monitor.Model.ApiClients.TwitchApiClient.<GetVods>d_41.MoveNext() in E:
\Programming\Git\Livestream.Monitor\Livestream.Monitor\Model\ApiClients
\ TwitchApiClient.cs:line 260
- End of stack trace from previous location where exception was thrown -
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
(Task task)
at Livestream.Monitor.ViewModels.VodListViewModel.<Ensureltems>d 52.MoveNext() in E:
\Programming\Git\Livestream.Monitor\Livestream.Monitor\ViewModels
\VodListViewModel.cs:line 240

```
Screenshot - ![sslsverror](https://github.com/user-attachments/assets/be60c2a8-f0e0-45fd-a285-6f4f7e3be717)

**Comment by laurencee** [comment]
Thanks for the report, been a long time since I looked at the vod viewer. Seems like something I missed updating a long time ago when the twitch API changed from v2/3 to helix (years ago).

I'll try to take a look at this when I have some time.

**Comment by laurencee** [comment]
Forgot to mention, the way I look for vods for some twitch channel is via the right click context menu on a twitch stream from the main window. That method still works correctly.

![image](https://github.com/user-attachments/assets/09977bff-be4e-4137-a13b-89f1022ef161)

**Comment by laurencee** [comment]
https://github.com/laurencee/Livestream.Monitor/releases/tag/2.14.0
